### ISSUE TITLE
CC0 support not implemented

### ISSUE THREAD

**Issue by BjornW** [creativecommons/wp-plugin-creativecommons#1]
This was sent to me by someone via email: 
'Why isn't CC0 https://creativecommons.org/publicdomain/zero/1.0/ license available?'

My answer so far: 
'We're using the CC API to grab the license selection, so either we're doing something wrong or CC is not making CC0 available via this method. I will add this to our bugtracker so we can look into it'

**Comment by brijn1975** [comment]
i dont understand.  all i know is this is my 7 th iphone 7 +.  call it what you will, but i am battling this "hack"  almost like its a full time job.  other devices are able to change my settings and control functions of my phone.  to what end.  my data last month jumped to 30 gbs.  92% on techknowledgy.  whats this about and who is doing this?

**Comment by r-a-y** [comment]
This is implemented, but in the Chooser, you have to specifically click on "CC0":

![Screenshot of Chooser with CC0 link highlighted](https://user-images.githubusercontent.com/505921/45919922-c4210f80-be8c-11e8-9d84-c82c92ac2893.png)

After you have clicked on CC0, you'll need to click on the the "Proceed" text-link so the script will add the license to the settings page.
