### ISSUE TITLE
Add copy and link re: relicensing

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/wp-plugin-creativecommons#10]
When changing the site-wide license, add copy that explains to the user that any content downloaded and/or re-used prior to changing the license will still (and always) be available to that user under the previous license, and that they may continue to share it, allowing other users to download and use that content under the previous licenses. There's probably an FAQ entry on this on our site -- let's link to it.

**Comment by BjornW** [comment]
The same goes for individual content, if someone licensed a post and changes the license, it also may be distributed under both licenses. Should we make this more clear in general or just as a warning when changing licenses?

**Comment by mattl** [comment]
@BjornW Looking at this :)

**Comment by BjornW** [comment]
Allright :)

**Comment by ahmadbilaldev** [comment]
To avoid this problem, the default license text now reads:

> Except were otherwise noted, this content is licensed by

In addition, the user can add additional text of their own for added clarity, if they so choose.
