### ISSUE TITLE
while choosing  CC0 Universal Public Domain Dedication license (CC0)  by default the link it should show lisence page of CC 

### ISSUE THREAD

**Issue by vestigialcode** [creativecommons/wp-plugin-creativecommons#102]
## Describe the bug
while choosing the  CC0 Universal Public Domain Dedication license (CC0)  in admin panel  the back link of cc0 should redirect to actual licenses page

## To Reproduce

1. Go to admin panel
2. Click on settings
3. Scroll down to Creative Commons
4. select the lisences>  CC0 Universal Public Domain Dedication license (CC0) >click footer>Save changes

## Expected behavior

May be backlink of the icon should redirect [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

## Screenshots

![Screenshot 2020-03-21 at 9 56 09 PM](https://user-images.githubusercontent.com/54473532/77231632-4abdc680-6bc2-11ea-8ac9-bf627e00a003.png)

## Desktop (please complete the following information)
 - OS: Linux
 - Browser: Firefox
 - Version : 2020.01.1

**Comment by hugosolar** [comment]
Thank you for pointing this out! 
there's a PR (#103) awaiting for review to fix this
