### ISSUE TITLE
Remove outdated language files

### ISSUE THREAD

**Issue by hugosolar** [creativecommons/wp-plugin-creativecommons#108]
## Problem Description
Since the last major update of the plugin, there are outdated files in the `language` folder 

## Solution Description
Investigate which files are outdated and remove them from the repository

**Comment by elaynelemos** [comment]
Hey! I would like to work on it if still available.

**Comment by kgodey** [comment]
go ahead @elaynelemos

**Comment by Cronus1007** [comment]
@hugosolar Shall i take over this issue.
