### ISSUE TITLE
Call to undefined method CreativeCommons::cc0_html_rdfa()

### ISSUE THREAD

**Issue by siccovansas** [creativecommons/wp-plugin-creativecommons#114]
## Describe the bug
When I use the CC0 license for an image I can't post/preview a post/page as I get a critical error.
When I look in the logs I see:

`NOTICE: PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method CreativeCommons::cc0_html_rdfa()`

When I search for `cc0_html_rdfa` in your GitHub repo I indeed don't see any method for `cc0_html_rdfa`, so the call indeed doesn't work. I only see the [method being called here](https://github.com/creativecommons/wp-plugin-creativecommons/blob/09ce39511e40405186b5dac68c7f6b5cfad866f9/includes/class-creativecommons-image.php#L461).

## To Reproduce
1. Go to the media library
2. Open an image and add a CC0 license
3. Create a new post and use the image as featured image
4. Hit preview or publish
5. See error

## Expected behavior
Don't see error

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 76.0

**Comment by siccovansas** [comment]
I don't want to ask for too much, but could a new version of the plugin be released so I can make use of this fix :)?

**Comment by kgodey** [comment]
@siccovansas we've released a new version of the plugin, sorry for the delay
