### ISSUE TITLE
get_attribution_options switch incomplete?

### ISSUE THREAD

**Issue by robmyers** [creativecommons/wp-plugin-creativecommons#12]
In class.creativecommons.org : get_attribution_options ,  I've seen it have no $attribution_options to return when the switch() hits the default and the if() in there fails.

I'm not sure whether this is the switch not capturing all the possibilities or bad options being passed in. I'll keep more of an eye out for it.

**Comment by ahmadbilaldev** [comment]
Removed dependency on `get_attribution_options()`.
