### ISSUE TITLE
Add loading="lazy" to the image tags

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [creativecommons/wp-plugin-creativecommons#126]
## Problem
Images in Wordpress 5.5 will be lazy-loaded [by default](https://make.wordpress.org/core/2020/07/14/lazy-loading-images-in-5-5/).  Needs the image loaded by this plugin to be lazy-loaded.

## Description
Wordpress 5.5 will load images as lazy by default. However, it doesn't cover all images. Only images in posts and some widgets. So this plugin would need to add 

`loading="lazy"`

to the `img` tags by default for consistency, with maybe a filter or a new setting to not load it lazy.

**Comment by vijayaraghavanramanan** [comment]
Should add that Wordpress had the filter `wp_lazy_loading_enabled`, so this plugin needn't add a filter of its own but check check if the Wordpress filter has been added by the site.

**Comment by decon-harsh** [comment]
I am working on plugins and wordpress for the first time , so as far as I understood I had to add a filter `add_filter($img, wp_lazy_loading_enabled, __return_true)` 
 targeting img tags in   includes/class-creativecommons-image.php. ?

**Comment by vijayaraghavanramanan** [comment]
@decon-harsh 

That filter is for Wordpress in general, and a site user can disable lazy loading by default by that filter, 

This plugin shouldn't enable or disable it using that filter. 

However, it will be useful, If there's some way to check if the site has disabled lazy load by default, the image tag by this plugin should also not load lazy. If the filter is true, then lazy load.

**Comment by hugosolar** [comment]
Hey @vijayaraghavanramanan! thank you for flagging this
I think we should check WordPress version as well considering compatibility backward
since this filter is introduced in 5.5 we may need to check if the filter exists in the current version
Also, if we decide to include all the images on the plugin we may need to filter the parameter to check whether the lazy load flag is true or not
does that make sense to you both?

**Comment by vijayaraghavanramanan** [comment]
@hugosolar 

Yeah good point about 5.5, although if we could figure out if the filter introduced in 5.5 has not been disabled, we can do it in just one go.

**Comment by vijayaraghavanramanan** [comment]
This might be of relevance:

https://github.com/WordPress/WordPress/blob/af523447f46c351cb27432813273049777fbb890/wp-includes/media.php#L1696-L1712

Maybe find if function exists and evaluate it to find if loading hasn't been disabled.

**Comment by hugosolar** [comment]
You're right!. that function should do the trick. So, there are two things to do here:

- Check if the function exists to enable lazy loading
- Filter the images on the plugin to add the `loading="lazy"` attribute

am I right?
