### ISSUE TITLE
Meta Field Formatting Is Unappealing 

### ISSUE THREAD

**Issue by robmyers** [creativecommons/wp-plugin-creativecommons#13]
Go to: Media > [an image] > Edit more details.

The fields we have added are being formatted into tables.

The titles are aligned to the middle of the table row, so they are vertically aligned between the text field and the help.

The text fields do not fill the available space, and so look truncated in comparison with the standard fields above them.

I've not found a way of reformatting these using the array() option syntax for fields, can we pass them as html and format them ourselves?

**Comment by BjornW** [comment]
Haven't looked at it yet, but perhaps you're missing some WordPress specific CSS classes on your fields? If not you can also add those classes yourself and add a custom admin css stylesheet.

**Comment by kgodey** [comment]
This issue is no longer valid. The format of the metadata fields is fine now.

Closing this issue.
