### ISSUE TITLE
Empty title adds extra padding

### ISSUE THREAD

**Issue by NicoHood** [creativecommons/wp-plugin-creativecommons#148]
## Description
This is how the widget looks with a title:
![grafik](https://user-images.githubusercontent.com/6888294/111376887-4f676e80-86a0-11eb-8660-f6baee331c9c.png)

And this is without (empty title highlighted):
![grafik](https://user-images.githubusercontent.com/6888294/111377028-7cb41c80-86a0-11eb-951a-17871d38f695.png)

You can clearly see, that there is additional padding to the top, cause the h2 is still there, but empty:
![grafik](https://user-images.githubusercontent.com/6888294/111377153-9d7c7200-86a0-11eb-94bd-5122d598b924.png)

## Reproduction
Add the widget without a title

## Environment
Wordpress 5.7
Generatepress (free) theme

## Additional context
The headline should be either removed or fallback to a default value.

**Comment by brylie** [comment]
Hei @NicoHood and @TimidRobot. I opened pull request #153 with a fix for this issue. Please let me know if that solution was close to what you had in mind.

**Comment by NicoHood** [comment]
@brylie Yes, that looks like it should fix my issue. Thanks for having a look at it!
