### ISSUE TITLE
a rel=license missing (machine readable license)

### ISSUE THREAD

**Issue by mandrasch** [creativecommons/wp-plugin-creativecommons#152]
Hey,

I did a quick test and it seems that the rel=”license” tag is not used?

Google (and other search engines) index it, it can be used in googles advanced search afterwards.

See e.g. https://smartcopying.edu.au/how-to-find-creative-commons-materials-using-google/

CC Choose tool also includes rel=license in the generated source code, see https://creativecommons.org/choose/

![Choose_a_License](https://user-images.githubusercontent.com/777278/116075820-b7dc3f00-a693-11eb-90c0-3fe539dbc6a8.png)

Thanks in advance!

Best regards,
Matthias

(Also posted this here a month ago https://wordpress.org/support/topic/a-rellicense-missing-machine-readable-license/)

**Comment by scottlimmer** [comment]
Anyone working on this?

**Comment by CRortyDG** [comment]
After installing the plugin to test this issue I see that rel="license" does exist on the footer versions of each of the licenses. It exists on both the link around the CC image and the link to the CC explanation - 

![footer-license](https://user-images.githubusercontent.com/115106247/194773111-ea14cfc2-17e8-4c60-b1e7-76e989f80cda.PNG)

But when the Gutenberg block of each of the CC types is used the CC image is no longer linked, and the explanation link is indeed missing the rel="license" - 

![footer-license](https://user-images.githubusercontent.com/115106247/194773238-13366412-028b-44ec-aa2a-dc15e7345ed3.PNG)

**Comment by CRortyDG** [comment]
In /includes/class-creativecommons.php It is evident where the footer content is defined and why it already includes rel="license", as this is in the function license_html_rdfa() where the HTML is directly defined. This function is called inside of print_license_html() where it gets the data needed and is originally called in /widgets/creativecommons-widget.php from the functions print_license_widget() | print_license_footer().

The footer is added through and add_action to wp_footer where it calls print_license_footer() as described above. 

![creativecommons-widgets](https://user-images.githubusercontent.com/115106247/194781875-63a56151-5248-4020-a251-b79be6950ee3.PNG)

I'm unsure running print_license_html() within print_license_widget() produces a different result than within print_license_footer().

This roadblock led me to find the block.js files defined within the /src/<license type> directories, these seem to include direct HTML that shows why the non-footer versions (widgets/blocks) are missing rel="license".

![by-blockjs](https://user-images.githubusercontent.com/115106247/194781993-6173337e-35f9-4946-b841-ef06d031a531.PNG)

But when including rel="license" in this HTML nothing changes on the front end, and I'm not quite sure where to go from here.
