### ISSUE TITLE
what does "author display name" radio button do?

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/wp-plugin-creativecommons#16]
can't figure it out. see:
![wp plugin](https://cloud.githubusercontent.com/assets/6394777/17383617/b9c200d4-598b-11e6-8a66-6d35985d5364.jpg)

**Comment by ahmadbilaldev** [comment]
Settings have been revamped.

![cc-settings](https://user-images.githubusercontent.com/19692245/63625818-3ad50880-c61a-11e9-88bf-5c47fc6100a3.png)
*Settings*
