### ISSUE TITLE
[RFC] deprecate `create-guten-block` scripts; use `@wordpress/scripts` instead

### ISSUE THREAD

**Issue by brylie** [creativecommons/wp-plugin-creativecommons#189]
When this project was started, we used the `create-guten-block` scripts to scaffold the code. Since that time, the `@wordpress/scripts` project has become the de facto standard for managing Gutenberg block projects/code. As such, we should consider the implications of adopting `@wordpress/scripts` for this project and deprecating `create-guten-block`.

**Comment by possumbilities** [comment]
Closing this issue since a number of things have shifted in context since it was originally opened. In several cases it won't be a simple 1:1, and as such a strategy to scope out the depth and breadth of this migration is needed first. That will be tracked here: #211
