### ISSUE TITLE
Composer Upgrade failed

### ISSUE THREAD

**Issue by cillacode** [creativecommons/wp-plugin-creativecommons#190]
Installing composer on Ubuntu terminal using the command "sudo apt install composer"  automatically installs composer 1, next i ran the command to install codesniffer "composer global require squizlabs/php_codesniffer" and got warning message  of Composer 1 is deprecated some packages will not be available.  ran the upgrade command of self-update --2, and returned self update not a command, then i uninstalled composer and entered the next command option "sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer"  which didn't respond.

1.  sudo apt install composer
2.  composer global require squizlabs/php_codesniffer
3. self-update --2
4. self update not a command

## Screenshot
![image](https://user-images.githubusercontent.com/54538525/136875446-1fa8be77-dc6c-4cf1-9462-0d6f2dc83edd.png)

**Comment by MuluhGodson** [comment]
Hello @cillacode 
The error suggest that a package is missing from your system. 
To install this package run the command:
`sudo apt install php8.0-xmlwriter`

**Comment by ArchanRD** [comment]
@possumbilities @TimidRobot This seems to be an issue with user's local environment and not with the plugin itself. Hence I'd suggest to close this issue as it seems to be out of our scope.

**Comment by possumbilities** [comment]
@ArchanRD Good spot, I agree. Closing.
