### ISSUE TITLE
[Feature] Expand docker-compose.yml file to include wpcli functionality

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/wp-plugin-creativecommons#200]
## Problem
See #199, this builds from there.

`````
MVP
At a minimum:

 - setup MySQL server (MariaDB preferably)
 - setup a web server (Apache), running latest WordPress files
 - make Web and DB server connect with each other appropriately
 - mount the db locally, so it persists
 - mount the WordPress install locally, so it persists
 - mount the wp-plugin-creativecommons plugin directory into the web server at wp-content/plugins/, so it can be user activated
-  include appropriate .gitignore additions so local mount points are not tracked ( ./dev/db & ./dev/wordpress)
 update documentation to reflect new docker compose one-liner referencing docker-compose.yml file
`````

The baseline Docker Image would benefit from having the fully featured functionality of the WP CLI command line utility bundled in. 

## Description
Once #199 is implemented, then as an expansion, WP CLI should be included in the `docker-compose.yml` file to allow more robust automated WP configuration and testing. At a minimum it can be included for devs to use as needed, but alternatively this opens the possibilities for later functionality to be baked in that would perform automated full WordPress installations or configuration patterns. 

### MVP 

- [ ] setup WP CLI img in `docker-compose.yml` file
- [ ] link to `web server` and `db`
- [ ] update any relevant documentation for use of wp cli in this context

## Alternatives
There are currently no known alternatives to WP CLI that I am aware of.

## Additional context
Will pull an image from the official WP CLI image variant found here: https://hub.docker.com/_/wordpress

### Decisions left to to make
- [ ] should there be any options exposed to aide in automatic installation setup by default? (single site, network, etc.)?
- [ ] If so, is there valid reason to automatically activate the `wp-plugin-creativecommons` plugin? (speeds up dev testing, BUT downside is that it leaves off the potential to test GUI based activation in WP version upgrades.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by ArchanRD** [comment]
@TimidRobot @possumbilities  I've created a PR for this issue. Please check it out!
