### ISSUE TITLE
[Bug] CC logos do not show on images, when using the WPZoom theme Inspiro  

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/wp-plugin-creativecommons#214]
## Description

[From wordpress.org > Anybody out there? Couple of bugs](https://wordpress.org/support/topic/anybody-out-there-couple-of-bugs/) (CSS formatting and syntax updated):
> I’m using the popular WPZoom theme Inspiro and the CC logos do not show on images unless I make a change in the customizer:
> ```css
> .cc-attribution-box-license {
>   width:6em;
> }
> ```

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by dennisgon** [comment]
Hi can you assign this issue to me? I will try to fix the bug

**Comment by ramanibuddha** [comment]
Hi can you assign any issue to me? I am ready to fix the bug
