### ISSUE TITLE
Plugin install error

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/wp-plugin-creativecommons#3]
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin install failed.
![wp plugin install fail](https://cloud.githubusercontent.com/assets/6394777/7523236/3f810b86-f4af-11e4-8ee0-cbce42c8c2f1.jpg)

**Comment by BjornW** [comment]
Could you specify more details such as: PHP version, webserver, OS and such?

**Comment by janeatcc** [comment]
Server: http://schoolofopen.p2pu.org
WordPress 4.1.5 running School of Open theme http://schoolofopen.p2pu.org/wp-admin/themes.php
I use a Mac OSX Yosemite 10.10.3 (14D136)

**Comment by mattl** [comment]
Do you know which version of WordPress that site is running? Also, do you
know who can update it to 4.2.2....

**Comment by janeatcc** [comment]
No... P2PU. It would be much easier if we just installed the plugin on our version of WP so I could take a look at it? That's the only reason I'm trying to install it.

**Comment by mattl** [comment]
The live website isn't a good testing place for plugins. Let me see what I
can do.
