### ISSUE TITLE
WP Plugin directory page needs updating?

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/wp-plugin-creativecommons#4]
See https://wordpress.org/plugins/creative-commons-license-widget/. If this GitHub is up to date, can we update the version in the plugin directory?

**Comment by BjornW** [comment]
Hi Jane, the one in the WordPress repository is such an old version that it will not be compatible with the new plugin here on Github. So before updating the old plugin we need to devise a strategy to deal with this.

**Comment by janeatcc** [comment]
I see. It's less important for us to update that particular page, than to get an ideal working version of the current plugin in the WP repository once it is ready. I can help get the latter, including WP promotion around it, once we can see that this current version of the plugin has the features we ideally desire. 

See issue https://github.com/creativecommons/wordpress-plugin/issues/3 and issue https://github.com/creativecommons/wordpress-plugin/issues/1.

I'd love to get the ball rolling on reviewing the plugin and suggesting fixes, improvements. Is this GitHub the best way to do that still? Who is the current lead(s) of this version of the WP plugin, if any? 

Fyi that we are exploring ways to more closely integrate CC/commons with WP.com as part of our [Platform Initiative](https://github.com/creativecommons/platform-initiative) and this .org plugin could help! 

cc @mattl

**Comment by mattl** [comment]
I will add prepping a release to our work schedule

**Comment by BjornW** [comment]
Yes, Github is the place for suggestions & issues. Feel free to use the issue tracker for this, at least for now. I'm the one who developed the current version of the plugin in collaboration with @tarmot. Not sure if that answers your question with regards to who leads the current version of the plugin..

**Comment by mattl** [comment]
@BjornW i assumed the CC Tech Team would handle releases and everyone would work on bugs when they could.

**Comment by janeatcc** [comment]
@mattl @BjornW great!

The idea is to use the .org plugin as a model for an eventual .com integration (eg. like Medium's). So we would want it to include the works, including logos, etc., even if the .com one would have to be built differently. So please include me on review of plugin before release! 

I'll use this GitHub to log issues, suggest improvements, etc., once I get a plugin installed and working..

**Comment by BjornW** [comment]
@mattl I have no problem with CC Tech Team handling releases :)  The first release needs to done very carefully due to the backwards incompatibility of the original plugin. I'm not sure what the best strategy for this would be.

**Comment by mattl** [comment]
My plan at least, was to make sure we use a unique name for this one, to
avoid any issues there. We may wind up doing a very basic release of the
old plugin to point people at this one ;)
