### ISSUE TITLE
Display of license in footer is poor

### ISSUE THREAD

**Issue by r-a-y** [creativecommons/wp-plugin-creativecommons#54]
I believe the default behavior of showing the license in the footer without any regard for the styling of the current site results in poor UX.

I think this behavior should be turned off or removed.  Let the site admin add the license widget so they can display the license wherever they want.

This also goes for the individual post license.  It should be displayed at the end of the post content and not in the site footer.

Current behavior for individual post license:

![Screenshot of post license in footer](https://user-images.githubusercontent.com/505921/45922075-f002bc00-beb1-11e8-8491-3edda9cece43.png)

**Comment by pravan** [comment]
There is no fail safe way to include the license text in the theme's footer. The only way we can display content in the footer is either with the help of widget areas in the footer or with the help of the wp_footer hook.

Currently, the plugin by default includes the license text with the help of wp_footer hook. You can also include the text in any one of the widget areas instead.

In your case also, you can probably include the creative commons license text widget in one of the footer widget areas for better results.

**Comment by r-a-y** [comment]
We created our own Creative Commons license plugin due to the lack of activity here.

You can find it here:
https://github.com/cuny-academic-commons/cac-creative-commons

Examples:

![Widget options](https://redmine.gc.cuny.edu/attachments/download/9043/license-widget-options.png)

![Post options](https://redmine.gc.cuny.edu/attachments/download/9046/license-post-options.png)

![Post display](https://redmine.gc.cuny.edu/attachments/download/9040/license-page.png)

![License selector - GIF](https://redmine.gc.cuny.edu/attachments/download/9039/license-chooser-new2.gif)

> There is no fail safe way to include the license text in the theme's footer. 

If the license is on a single post page, you can add it at the end of the post with the `the_content` filter.

Furthermore, theme developers can override the look of the license output by overriding the default templates that are shipped with the plugin.

> The only way we can display content in the footer is either with the help of widget areas in the footer or with the help of the wp_footer hook.

Agreed.  The widget option is only applicable if it is a site license though.
