### ISSUE TITLE
Display license text in a widget

### ISSUE THREAD

**Issue by mattl** [creativecommons/wp-plugin-creativecommons#6]
The current footer display doesn't work with the current default theme

**Comment by tarmot** [comment]
Right, the 2015 theme does something silly. Options are to disable the footer view and expect people to add the widget somewhere, or try to debug the footer location. But making theme-specific fixes sounds like a bad idea.

**Comment by mattl** [comment]
Can we add the licensing blog as a WP widget? All themes worth their salt support widgets.

**Comment by tarmot** [comment]
There is a widget. Of course. But in case the widget hasn't been deployed by the blog admin, the plugin will display the license in the footer. Just to make sure that the license is always displayed. If this is not necessary, we can simply disable the footer display, and possibly add a warning into the backend in case the license widget has not been deployed.

**Comment by ahmadbilaldev** [comment]
Fixed. See #54.
