### ISSUE TITLE
Single instance causes two plugins in dashboard

### ISSUE THREAD

**Issue by ChoccyHobNob** [creativecommons/wp-plugin-creativecommons#71]
**Describe the bug**
Two plugins are presented in the dashboard plugins page

both `creativecommons.php` and `license-return.php` contain a Plugin-Name: field

**To Reproduce**
1. Upload the creativecommons folder
2. go to Plugins in Dashboard.

**Expected behavior**
Just the one plugin to enable

**Screenshots**
![Screenshot 2019-07-21 at 11 53 56](https://user-images.githubusercontent.com/12753/61594192-6cd3f480-abae-11e9-9c96-dc2ec4f8a758.jpg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari
 - Version 12.1.1

**Comment by ahmadbilaldev** [comment]
Bug fixed. It was a faulty header in the `license-return.php`. It should not reproduce now. If you can, please confirm by uploading the plugin again. Thank you for the feedback, let us know if you encounter any other problem, it helps.

**Comment by ChoccyHobNob** [comment]
That's better, thanks. 

Might want to update the release package?...

**Comment by ahmadbilaldev** [comment]
Sure, we will.
