### ISSUE TITLE
Internationalize the plugin

### ISSUE THREAD

**Issue by lenasterg** [creativecommons/wp-plugin-creativecommons#80]
Hi. 
Thanks for the great work.
Currently the plugin doesn't follows the WP guidelines for intenationalization https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/
so it can't be translated in other languages. 

Bests Lena

**Comment by nemobis** [comment]
Many Wikimedia blogs need to attribute CC-BY and CC-BY-SA works, so it would be nice to have the translations on translatewiki.net. https://translatewiki.net/wiki/Translating:New_project

**Comment by cmlnet** [comment]
Internationalisation would indeed be great! :-)

**Comment by vestigialcode** [comment]
I would like to work on this feature..

**Comment by kgodey** [comment]
@vestigialcode go ahead.

**Comment by zhaofeng-shu33** [comment]
I find there are already Dutch language `nl_NL.po`.

**Comment by zhaofeng-shu33** [comment]
I have opened a WIP PR for this issue, any suggestions or feedback?
